version: '3'
services:
   db:
     image: percona:8
     container_name: db
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
       MYSQL_DATABASE: "${DB_NAME}"
       MYSQL_USER: "${APP_USERNAME}"
       MYSQL_PASSWORD: "${APP_USERNAME_PASSWORD}"

   app:
     image: wordpress:latest
     container_name: app
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: "${APP_USERNAME}"
       WORDPRESS_DB_PASSWORD: "${APP_USERNAME_PASSWORD}"
       WORDPRESS_DB_NAME: "${DB_NAME}"
     depends_on:
       - db
     links:
       - db

   nginx:
     image: nginx:latest
     container_name: nginx
     volumes:
       - ./nginx/default.conf:/tmp/default.template
     depends_on:
       - app
     restart: always
     entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
     build:
       context: .
       dockerfile: Dockerfile-nginx
     ports:
       - "80:80"
     depends_on:
       - app
     links:
       - app
    